name: Release ModLoaderSolution

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'mod-loader/mod-loader-solution/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: |
          msbuild mod-loader/mod-loader-solution/ModLoaderSolution.sln /p:Configuration=Release /p:WarningsAsErrors=false /p:WarningLevel=1 /nologo /v:m
          # Move the compiled output
          $source = "$Env:GITHUB_WORKSPACE\mod-loader\mod-loader-solution\bin\Release\ModLoaderSolution.dll"
          $dest = "$Env:GITHUB_WORKSPACE\ModLoaderSolution.bin"
          Move-Item -Path $source -Destination $dest -Force

      - name: Upload solution
        uses: actions/upload-artifact@v4
        with:
          name: ModLoaderSolution
          path: ModLoaderSolution.bin

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: nohumanman/nohumanman.com
          ref: 'main'
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete existing ModLoaderSolution
        run: rm -f ${{ github.workspace }}/static/ModLoaderSolution.bin

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ModLoaderSolution
          path: ${{ github.workspace }}/static/ModLoaderSolutionFiles

      - name: Push to nohumanman.com
        run: |
          url="https://api.github.com/repos/matthew-w-bayley/descenders-modkit/commits/main"
          response=$(curl -s -H "Accept: application/vnd.github.v3+json" $url)
          commit_hash=$(echo $response | jq -r '.sha')
          
          mv ${{ github.workspace }}/static/ModLoaderSolutionFiles/ModLoaderSolution.bin ${{ github.workspace }}/static/ModLoaderSolution.bin
          rm -rf ${{ github.workspace }}/static/ModLoaderSolutionFiles/
          
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update ModLoaderSolution from $commit_hash"
          git push origin main
          
          # notify discord server
          json='{"username": "Descenders Modkit", "content": "The modkit client file has updated to a new version!\nhttps://github.com/matthew-w-bayley/descenders-modkit/commit/'"$commit_hash"'"}'
          curl -H "Content-Type: application/json" -d "$json" ${{ secrets.DISCORD_WEBHOOK }}
