# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .mod-loader-solution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE/mod-loader-solution

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore ModLoaderSolution.sln

    - name: Build Solution
      run: |
        msbuild.exe ModLoaderSolution.sln