# This workflow will build a .NET project and push it to release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release ModLoaderSolution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Solution
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           $warnings = .\MSBuild.exe $Env:GITHUB_WORKSPACE\mod-loader-solution\ModLoaderSolution.sln /p:WarningsAsErrors=true /p:WarningLevel=4  /nologo /v:q
           if ($warnings -gt 0) { exit 1 }
           mv $Env:GITHUB_WORKSPACE\mod-loader-solution\bin\Debug\ModLoaderSolution.dll .\ModLoaderSolution.bin
      - name: Upload solution
        uses: actions/upload-artifact@v2
        with:
          name: ModLoaderSolution
          path: ${{ github.workspace }}/ModLoaderSolution.bin

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ModLoaderSolution
          path: ${{ github.workspace }}/ModLoaderSolution.bin

      - name: Push to repository
        uses: actions/upload-artifact@v2
        with:
          repository: nohumanman.com
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/ModLoaderSolution.bin
          name: static/ModLoaderSolution.bin
