name: Running Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Create virtual environment
        run: |
          python -m venv ./server/src/.venv
          source ./server/src/.venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f server/src/requirements.txt ]; then pip install -r server/src/requirements.txt; fi

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/server/src/
          python -m unittest discover -s ./server/tests -p "*_test.py"
